### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by mingwayzhang** [Bareflank/extended_apis#111]
I tried to compile this repository with the lastest version of the hypervisor.

I have met the following issue:

In file included from /home/mingwei/tools/bareflank_extended_apis_repo/bfack/ack.cpp:20:0:
/home/mingwei/tools/bareflank_repo/bfintrinsics/include/intrinsics.h:25:18: error: ‘g_rsdp’ declared as an ‘inline’ variable
 inline uintptr_t g_rsdp = 0;
                  ^

Would you fix this one?

**Comment by rianquinn** [comment]
Huh, that is strange. I will look into that. That basically means that the c++17 flag was not provided to the compiler, but it should be.

**Comment by rianquinn** [comment]
@mingwayzhang What compiler are you using?

**Comment by mingwayzhang** [comment]
My compiler is clang++-5.0

**Comment by rianquinn** [comment]
@mingwayzhang Which version of GCC are you using? Clang is used to compile VMM, but for native code (that is not cross-compiled), GCC is used (like bfm and bfack).

**Comment by mingwayzhang** [comment]
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by mingwayzhang** [comment]
I switched to gcc-7. Now it is working! Thanks!

**Comment by rianquinn** [comment]
No problem. Let me know if you need any more help.
