### ISSUE TITLE
VMExit on External Interrupts

### ISSUE THREAD

**Issue by adilahmad17** [Bareflank/extended_apis#117]
Hey,

I am trying to trap external interrupts from the hypervisor-end and my module is as follows:

```
    vcpu(vcpuid::type id) :
        eapis::intel_x64::vcpu{id}
    {
        ...
        eapis()->add_external_interrupt_handler(
            external_interrupt_handler::handler_delegate_t::create<vcpu,
            &vcpu::external_interrupt_handler>(this)
        );
    }

    bool
    external_interrupt_handler(gsl::not_null<vmcs_t *> vmcs, external_interrupt_handler::info_t &info)
    {
      bfignored(vmcs);
      bfignored(info);
      eapis()->external_interrupt()->disable_exiting();
      return false;
    }
```

But my system (Linux) hangs each time I do so. Can someone guide me as to what the issue could be?

Also, I am using an old release RC 2.0.2. Please let me know if the release version might have
something to do with this.

Thanks!

**Comment by rianquinn** [comment]
The following provides an example of how to do this:
https://github.com/Bareflank/hypervisor/blob/master/bfvmm/integration/arch/intel_x64/vmexit/external_interrupt/trap_all_interrupts.cpp

I think the reason your system is likely hanging is that you are returning
false, which tells the base APIs that you are not handling the external
interrupt, but the base has no way to do this on its own.
- Rian

**Comment by rianquinn** [comment]
Oh, and you also have to queue the interrupt. If you don't, the interrupt will be dropped, which will likely cause issues. You can still disable exiting after that, just make sure you actually handle the interrupt you trapped on.

**Comment by adilahmad17** [comment]
Oh, thanks a bunch for the pointer. The issue was that I wasn't queuing the interrupt and since i am using an old release, I also seem to have to trap on interrupt-windows in order to dump my internal queue of interrupts onto the guest.

Thanks a bunch for the great work!
