### ISSUE TITLE
[Q] Logging/Writing to a file from exit handler

### ISSUE THREAD

**Issue by Randshot** [Bareflank/extended_apis#21]
Hi, it's me again.
This time I want to write to file from within my exit handler.
I know that this is probably a very bad idea, but I need it in my case.

I saw that you have a **file** class inside **bfm** but I can't seem to include it in my module.
Do I need to add something to my xxx.modules file before being able to include it?

Randshot

**Comment by rianquinn** [comment]
There is no file access from within the VMM. To do such a thing, you would have to map in the OS's kernel, and then locate the APIs that you want to use to write the file.

**Comment by rianquinn** [comment]
Even if you could pull that off, it's not advised because the OS APIs require interrupts which are disabled in the VMM. For more information please see the following:

https://github.com/Bareflank/hypervisor/issues/260

**Comment by Randshot** [comment]
Hm, ok. I will then likely end up using the DATA IOCTL mode to accomplish this.

**Comment by rianquinn** [comment]
Yeah, that's a better direction.
